plugins:
  daily_challenge_enabled:
    default: true
    client: true
  daily_challenge_mod_access_enabled:
    default: true
    type: bool
    client: true
  daily_challenge_category_mod_access_enabled:
    default: true
    type: bool
    client: true
  daily_challenge_bot_username:
    default: ""
    type: string
    client: true
